version: '3.1'

services:

  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rx_mastermind_server
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rx_mastermind_server -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5